/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalculatorResultsRouteImport } from './routes/calculator.results'
import { Route as LearnSectionIdRouteImport } from './routes/learn.section.$id'
import { Route as LearnArticleIdRouteImport } from './routes/learn.article.$id'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorResultsRoute = CalculatorResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => CalculatorRoute,
} as any)
const LearnSectionIdRoute = LearnSectionIdRouteImport.update({
  id: '/section/$id',
  path: '/section/$id',
  getParentRoute: () => LearnRoute,
} as any)
const LearnArticleIdRoute = LearnArticleIdRouteImport.update({
  id: '/article/$id',
  path: '/article/$id',
  getParentRoute: () => LearnRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRouteWithChildren
  '/compare': typeof CompareRoute
  '/learn': typeof LearnRouteWithChildren
  '/profile': typeof ProfileRoute
  '/calculator/results': typeof CalculatorResultsRoute
  '/learn/article/$id': typeof LearnArticleIdRoute
  '/learn/section/$id': typeof LearnSectionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRouteWithChildren
  '/compare': typeof CompareRoute
  '/learn': typeof LearnRouteWithChildren
  '/profile': typeof ProfileRoute
  '/calculator/results': typeof CalculatorResultsRoute
  '/learn/article/$id': typeof LearnArticleIdRoute
  '/learn/section/$id': typeof LearnSectionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRouteWithChildren
  '/compare': typeof CompareRoute
  '/learn': typeof LearnRouteWithChildren
  '/profile': typeof ProfileRoute
  '/calculator/results': typeof CalculatorResultsRoute
  '/learn/article/$id': typeof LearnArticleIdRoute
  '/learn/section/$id': typeof LearnSectionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculator'
    | '/compare'
    | '/learn'
    | '/profile'
    | '/calculator/results'
    | '/learn/article/$id'
    | '/learn/section/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculator'
    | '/compare'
    | '/learn'
    | '/profile'
    | '/calculator/results'
    | '/learn/article/$id'
    | '/learn/section/$id'
  id:
    | '__root__'
    | '/'
    | '/calculator'
    | '/compare'
    | '/learn'
    | '/profile'
    | '/calculator/results'
    | '/learn/article/$id'
    | '/learn/section/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculatorRoute: typeof CalculatorRouteWithChildren
  CompareRoute: typeof CompareRoute
  LearnRoute: typeof LearnRouteWithChildren
  ProfileRoute: typeof ProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator/results': {
      id: '/calculator/results'
      path: '/results'
      fullPath: '/calculator/results'
      preLoaderRoute: typeof CalculatorResultsRouteImport
      parentRoute: typeof CalculatorRoute
    }
    '/learn/section/$id': {
      id: '/learn/section/$id'
      path: '/section/$id'
      fullPath: '/learn/section/$id'
      preLoaderRoute: typeof LearnSectionIdRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/article/$id': {
      id: '/learn/article/$id'
      path: '/article/$id'
      fullPath: '/learn/article/$id'
      preLoaderRoute: typeof LearnArticleIdRouteImport
      parentRoute: typeof LearnRoute
    }
  }
}

interface CalculatorRouteChildren {
  CalculatorResultsRoute: typeof CalculatorResultsRoute
}

const CalculatorRouteChildren: CalculatorRouteChildren = {
  CalculatorResultsRoute: CalculatorResultsRoute,
}

const CalculatorRouteWithChildren = CalculatorRoute._addFileChildren(
  CalculatorRouteChildren,
)

interface LearnRouteChildren {
  LearnArticleIdRoute: typeof LearnArticleIdRoute
  LearnSectionIdRoute: typeof LearnSectionIdRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnArticleIdRoute: LearnArticleIdRoute,
  LearnSectionIdRoute: LearnSectionIdRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculatorRoute: CalculatorRouteWithChildren,
  CompareRoute: CompareRoute,
  LearnRoute: LearnRouteWithChildren,
  ProfileRoute: ProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
